---
asset_groups:
  core:
    - /captcha/base
    - /catalog/category/cache
    - /catalog/product/cache
    - /css
    - /css_secure
    - /import
    - /js
    - /js_secure
    - /tmp
  common_modules: {}
database_table_groups:
  core:
    - adminnotification_inbox
    - admin_passwords
    - admin_user
    - admin_user_session
    - api2_acl_user
    - cache
    - cache_tag
    - captcha_log
    - catalog_category_anc_categs_index_tmp
    - catalog_category_anc_products_index_tmp
    - catalog_category_flat_cl
    - catalog_category_product_cat_cl
    - catalog_category_product_index_cl
    - catalog_compare_item
    - catalog_product_flat_cl
    - catalog_product_index_eav_decimal_tmp
    - catalog_product_index_eav_tmp
    - catalog_product_index_price_bundle_opt_tmp
    - catalog_product_index_price_bundle_sel_tmp
    - catalog_product_index_price_bundle_tmp
    - catalog_product_index_price_cfg_opt_tmp
    - catalog_product_index_price_downlod_tmp
    - catalog_product_index_price_final_tmp
    - catalog_product_index_price_opt_tmp
    - catalog_product_index_price_opt_agr_tmp
    - catalog_product_index_price_cl
    - catalog_product_index_price_tmp
    - cataloginventory_stock_status_cl
    - cataloginventory_stock_status_tmp
    - catalogsearch_fulltext_cl
    - core_cache
    - core_cache_tag
    - core_session
    - coupon_aggregated
    - coupon_aggregated_order
    - coupon_aggregated_updated
    - cron_schedule
    - customer_address_entity
    - customer_address_entity_datetime
    - customer_address_entity_decimal
    - customer_address_entity_int
    - customer_address_entity_text
    - customer_address_entity_varchar
    - customer_entity
    - customer_entity_datetime
    - customer_entity_decimal
    - customer_entity_int
    - customer_entity_text
    - customer_entity_varchar
    - enterprise_customer_sales_order
    - enterprise_customer_sales_order_address
    - enterprise_customer_sales_quote
    - enterprise_customer_sales_quote_address
    - enterprise_customerbalance
    - enterprise_customerbalance_history
    - enterprise_customersegment_customer
    - enterprise_customersegment_event
    - enterprise_giftcardaccount
    - enterprise_giftcardaccount_history
    - enterprise_giftcardaccount_pool
    - enterprise_giftregistry_data
    - enterprise_giftregistry_entity
    - enterprise_giftregistry_item
    - enterprise_giftregistry_label
    - enterprise_giftregistry_person
    - enterprise_giftregistry_type
    - enterprise_giftregistry_type_info
    - enterprise_invitation
    - enterprise_invitation_status_history
    - enterprise_invitation_track
    - enterprise_logging_event
    - enterprise_logging_event_changes
    - enterprise_logging_event_track
    - enterprise_reminder_rule
    - enterprise_reminder_rule_coupon
    - enterprise_reminder_rule_coupon
    - enterprise_reminder_rule_log
    - enterprise_reminder_rule_website
    - enterprise_reward
    - enterprise_reward_history
    - enterprise_rma
    - enterprise_rma_grid
    - enterprise_rma_item_entity
    - enterprise_rma_item_entity_datetime
    - enterprise_rma_item_entity_decimal
    - enterprise_rma_item_entity_int
    - enterprise_rma_item_entity_text
    - enterprise_rma_item_entity_text
    - enterprise_rma_item_form_attribute
    - enterprise_rma_shipping_label
    - enterprise_rma_status_history
    - enterprise_sales_creditmemo_grid_archive
    - enterprise_sales_invoice_grid_archive
    - enterprise_sales_order_grid_archive
    - enterprise_sales_shipment_grid_archive
    - enterprise_staging_log
    - enterprise_url_rewrite_category_cl
    - enterprise_url_rewrite_product_cl
    - enterprise_url_rewrite_redirect_cl
    - enterprise_url_rewrite
    - gift_message
    - importexport_importdata
    - import_history
    - index_event
    - index_process_event
# @todo Did Mage2 remove the log tables?
#    - log_customer
#    - log_quote
#    - log_summary
#    - log_summary_type
#    - log_url
#    - log_url_info
#    - log_visitor
#    - log_visitor_info
    - newsletter_problem
    - newsletter_queue
    - newsletter_queue_link
    - newsletter_queue_store_link
    - newsletter_subscriber
    - newsletter_subscriber_backup
    - oauth_consumer
    - oauth_nonce
    - oauth_token
    - paypal_payment_transaction
    - paypal_settlement_report
    - paypal_settlement_report_row
    - persistent_session
    - processmanager_process_log
    - product_alert_price
    - product_alert_stock
    - quote
    - quote_address
    - quote_address_item
    - quote_id_mask
    - quote_item
    - quote_item_options
    - quote_payment
    - quote_shipping_rate
    - rating_option_vote
    - rating_option_vote_aggregated
    - report_compared_product_index
    - report_event
    - report_viewed_product_aggregated_daily
    - report_viewed_product_aggregated_monthly
    - report_viewed_product_aggregated_yearly
    - report_viewed_product_index
    - review
    - review_detail
    - review_entity_summary
    - review_store
    - sales_bestsellers_aggregated_daily
    - sales_bestsellers_aggregated_monthly
    - sales_bestsellers_aggregated_yearly
    - sales_billing_agreement
    - sales_billing_agreement_order
    - sales_creditmemo
    - sales_creditmemo_comment
    - sales_creditmemo_grid
    - sales_creditmemo_item
    - sales_invoice
    - sales_invoice_comment
    - sales_invoice_grid
    - sales_invoice_item
    - sales_order
    - sales_order_address
    - sales_order_grid
    - sales_order_item
    - sales_order_payment
    - sales_order_status_history
    - sales_quote
    - sales_quote_address
    - sales_quote_address_item
    - sales_quote_item
    - sales_quote_item_option
    - sales_quote_payment
    - sales_quote_shipping_rate
    - sales_shipment
    - sales_shipment_comment
    - sales_shipment_grid
    - sales_shipment_item
    - sales_shipment_track
    - sales_invoiced_aggregated
    - sales_invoiced_aggregated_order
    - sales_order_aggregated_created
    - sales_order_aggregated_updated
    - sales_order_tax
    - sales_order_tax_item
    - sales_payment_transaction
    - sales_recurring_profile
    - sales_recurring_profile_order
    - sales_refunded_aggregated
    - sales_refunded_aggregated_order
    - sales_shipping_aggregated
    - sales_shipping_aggregated_order
    - salesrule_coupon_usage
    - salesrule_customer
    - sendfriend_log
    - sequence_creditmemo_0
    - sequence_creditmemo_1
    - sequence_invoice_0
    - sequence_invoice_1
    - sequence_order_0
    - sequence_order_1
    - sequence_shipment_0
    - sequence_shipment_1
    - session
    - sitemap
    - tax_order_aggregated_created
    - tax_order_aggregated_updated
    - wishlist
    - wishlist_item
    - wishlist_item_option
  common_modules: {}

template_vars:
  install_date: Fri, 08 Jun 2012 19:59:58 +0000 # This is not really important for Magento functionality. Any default date is fine
